//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetMgtSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Users = new HashSet<User>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Directorate { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
