//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetMgtSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.IncidentLogs = new HashSet<IncidentLog>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateEmployed { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public Nullable<int> VehicleAssociate { get; set; }
        public string DelFlg { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual DriverEmployer DriverEmployer { get; set; }
        public virtual ICollection<IncidentLog> IncidentLogs { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual FleetLocation FleetLocation { get; set; }
    }
}
