//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetMgtSolution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleetMgtSysDBEntities : DbContext
    {
        public FleetMgtSysDBEntities()
            : base("name=FleetMgtSysDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Departments { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<DriverEmployer> DriverEmployers { get; set; }
        public DbSet<IncidentLog> IncidentLogs { get; set; }
        public DbSet<InsuranceCompany> InsuranceCompanies { get; set; }
        public DbSet<TrackerCompany> TrackerCompanies { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<VehicleIncidenceType> VehicleIncidenceTypes { get; set; }
        public DbSet<VehicleMaker> VehicleMakers { get; set; }
        public DbSet<VehicleType> VehicleTypes { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<Trip> Trips { get; set; }
        public DbSet<SmsNotification> SmsNotifications { get; set; }
        public DbSet<FleetLocation> FleetLocations { get; set; }
        public DbSet<Batch> Batches { get; set; }
    }
}
