//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetMgtSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentLog
    {
        public int ID { get; set; }
        public Nullable<int> IncidentTypeID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
        public Nullable<int> AssociatedDriver { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> AssociatedVehicle { get; set; }
        public Nullable<System.DateTime> VehMaintenanceDate { get; set; }
        public Nullable<decimal> MileageAtMaintenance { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual VehicleIncidenceType VehicleIncidenceType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
