//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetMgtSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Trips = new HashSet<Trip>();
            this.Trips1 = new HashSet<Trip>();
            this.Trips2 = new HashSet<Trip>();
        }
    
        public int ID { get; set; }
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string RoleName { get; set; }
        public string Email { get; set; }
        public string DepartmentName { get; set; }
        public string Directorate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isHoD { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
        public virtual ICollection<Trip> Trips1 { get; set; }
        public virtual ICollection<Trip> Trips2 { get; set; }
        public virtual FleetLocation FleetLocation { get; set; }
    }
}
