//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetMgtSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Drivers = new HashSet<Driver>();
            this.Trips = new HashSet<Trip>();
            this.IncidentLogs = new HashSet<IncidentLog>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MarkerID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public Nullable<int> AssociatedDriver { get; set; }
        public string PlateNo { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseExprDate { get; set; }
        public string InsuranceNo { get; set; }
        public Nullable<System.DateTime> InsuranceExprDate { get; set; }
        public Nullable<int> InsuranceCompany { get; set; }
        public Nullable<int> TrackerCompany { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public Nullable<decimal> MileageAtLastService { get; set; }
        public string ChasisNo { get; set; }
        public string EngineNo { get; set; }
        public string DelFlg { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual InsuranceCompany InsuranceCompany1 { get; set; }
        public virtual TrackerCompany TrackerCompany1 { get; set; }
        public virtual VehicleMaker VehicleMaker { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
        public virtual ICollection<IncidentLog> IncidentLogs { get; set; }
        public virtual FleetLocation FleetLocation { get; set; }
    }
}
